services:
  mongo:
    image: mongo:8.0.5
    volumes:
      - mongodb:/data/db
    ports:
      - 27021:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    command: ['--auth']

volumes:
  mongodb: